- name: Install dependencies
  yum:
    name: 
      - gcc-c++
      - openssl-devel
      - readline-devel
      - zlib-devel
      - curl-devel
      - libyaml-devel
      - libffi-devel

- name: Install httpd
  yum:
    name: 
      - httpd
      - httpd-devel

- name: Install passenger
  gem:
    name: passenger
    executable: "{{gem_path}}"
    user_install: no

- name: Install passenger apache2 module
  shell: passenger-install-apache2-module --auto

- name: Get passenger apache2 module snippet
  shell: passenger-install-apache2-module --snippet
  register: passenger_snippet

- name: Add redmine.conf
  template:
    src: redmine.conf.j2
    dest: /etc/httpd/conf.d/redmine.conf

- name: Change DocumentRoot
  lineinfile:
    state: present
    dest: /etc/httpd/conf/httpd.conf
    regexp: '^DocumentRoot'
    line: DocumentRoot /var/lib/redmine/public
    backup: yes

- name: Restart httpd
  service:
    name: httpd
    state: restarted
